const cores = ["aliceblue","antiquewhite","aqua","aquamarine","azure","beige","bisque","black","blanchedalmond","blue","blueviolet","brown","burlywood","cadetblue","chartreuse","chocolate","coral","cornflowerblue","cornsilk","crimson","cyan","darkblue","darkcyan","darkgoldenrod","darkgray","darkgreen","darkkhaki","darkmagenta","darkolivegreen","darkorange","darkorchid","darkred","darksalmon","darkseagreen","darkslateblue","darkslategray","darkturquoise","darkviolet","deeppink","deepskyblue","dimgray","dodgerblue","firebrick","floralwhite","forestgreen","fuchsia","gainsboro","ghostwhite","gold","goldenrod","gray","green","greenyellow","honeydew","hotpink","indianred","indigo","ivory","khaki","lavender","lavenderblush","lawngreen","lemonchiffon","lightblue","lightcoral","lightcyan","lightgoldenrodyellow","lightgray","lightgreen","lightpink","lightsalmon","lightseagreen","lightskyblue","lightslategray","lightsteelblue","lightyellow","lime","limegreen","linen","magenta","maroon","mediumaquamarine","mediumblue","mediumorchid","mediumpurple","mediumseagreen","mediumslateblue","mediumspringgreen","mediumturquoise","mediumvioletred","midnightblue","mintcream","mistyrose","moccasin","navajowhite","navy","oldlace","olive","olivedrab","orange","orangered","orchid","palegoldenrod","palegreen","paleturquoise","palevioletred","papayawhip","peachpuff","peru","pink","plum","powderblue","purple","rebeccapurple","red","rosybrown","royalblue","saddlebrown","salmon","sandybrown","seagreen","seashell","sienna","silver","skyblue","slateblue","slategray","snow","springgreen","steelblue","tan","teal","thistle","tomato","turquoise","violet","wheat","white","whitesmoke","yellow","yellowgreen"];
const quant = cores.length;

const nomes = ["Azul Alice","Branco Antigo","Água","Azul Marinho","Azul Celeste","Bege","Bisque","Preto","Amêndoa Branqueada","Azul","Azul Violeta","Marrom","Marrom Sarrado","Azul Cadete","Chartreuse","Chocolate","Coral","Azul Centáurea","Casquinha Milho","Carmesim","Ciano","Azul Escuro","Ciano Escuro","Ouro Velho Escuro","Cinza Escuro","Verde Escuro","Caqui Escuro","Magenta Escuro","Verde Oliva Escuro","Laranja Escuro","Orquídea Escura","Vermelho Escuro","Salmão Escuro","Verde Mar Escuro","Azul Ardósia Escuro","Cinza Ardósia Escuro","Turquesa Escura","Violeta Escura","Rosa Profundo","Azul Céu Profundo","Cinza Fosco","Azul Dodger","Tijolo de Fogo","Branco Floral","Verde Floresta","Fúcsia","Gainsboro","Branco Fantasma","Ouro","Ouro Velho","Cinza","Verde","Verde Amarelado","Mel de Abelha","Rosa Choque","Vermelho Indiano","Índigo","Marfim","Caqui","Lavanda","Lavanda Rum","Verde Grama","Creme de Limão","Azul Claro","Coral Claro","Ciano Claro","Amarelo Dourado Claro Claro","Cinza Claro","Verde Claro","Rosa Claro","Salmão Claro","Verde Mar Claro","Azul Céu Claro","Cinza Ardósia Claro","Azul Aço Claro","Amarelo Claro","Lima","Verde Lima","Linho","Magenta","Bordô","Azul Marinho Médio","Azul Médio","Orquídea Média","Roxo Médio","Verde Mar Médio","Azul Ardósia Médio","Verde Primavera Médio","Turquesa Média","Vermelho Violeta Médio","Azul Meia-Noite","Creme de Menta","Rosa Geado","Mocassim","Branco Navajó","Marinho Marinho","Renda Antiga","Oliva","Oliva Parda","Laranja","Vermelho Laranja","Orquídea","Ouro Velho Pálido","Verde Pálido","Turquesa Pálida","Vermelho Violeta Pálido","Mamão","Pêssego","Peru","Rosa","Ameixa","Azul Poeira","Roxo","Roxo Rebecca","Vermelho","Marrom Sujo","Azul Real","Marrom Sela","Salmão","Marrom Areia","Verde Mar","Casca Mar","Sienna","Prata","Azul Céu","Azul Ardósia","Cinza Ardósia","Neve","Verde Primavera","Azul Aço","Bronzeado","Verde Azulado","Cardo","Tomate","Turquesa","Violeta","Trigo","Branco","Branco Fumaça","Amarelo","Verde Amarelo"];

document.querySelector('.mudar-cor button').addEventListener('click', () => {

    const num = Math.floor(Math.random() * quant);
    
    document.querySelector('main').style.backgroundColor = cores[num];
    document.querySelector('h2 span').textContent = nomes[num];
})